# Generated by Django 4.0.4 on 2024-01-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredits',
            name='is_premium_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='user_allowed_words',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
